### PR TITLE
Update website

### LINKED ISSUE #129: Make TOC sticky
Should stay on screen when you scroll.

Used to work but I broke it oops.

### PR DESCRIPTION
**Pull request by wallamide**
# Objectives: 

- Fix some styling issues across the site, using PRs #227/#228 and adding visual symmetry to the front page 
Screenshot from 2023-02-23 12-43-41
- Add support for css3 and css4 compatibility
- Update projects page to represent current development cycles
image
- Fix #129

### CODE REVIEW

**Comment by wallamide** [comment]
we'll need to fix the zola build issue shortly, just waiting for getzola/zola#2103 testing to finish

**Review by plof27 — CHANGES_REQUESTED** [review]
The code looks all good, but I have some UI issues

The sticky TOC is really close to the top of the page:
image

This should really have some additional margin on it, perhaps quite a bit (24+ px)

I really dislike the "growing cards"
image

While they're very neat, they don't serve the purpose. 
- Hover highlights should be subtle, because you really don't need much. This is just too significant a change
- It's too much of a change on hover, which ultimately makes them distract instead of help
- The growing means that UI elements move right after you hover over them, which makes it much harder to click things accurately (like the title or tags)
- The title text also grows, which, when combined with the color change, looks very odd
- I just don't think they look very good. I honestly think it looked better before (although the nested link stuff is pretty good)

Unless I hear some pretty strong arguments, I'm not comfortable merging this while these are in.

**Comment by alice-i-cecile** [comment]
Agreed on both points. The hover grow is neat, and technically impressive, but I think ultimately negative value.

I also wasn't getting the correct redirect to individual blog posts in the preview: I think we may have the paths set up wrong there somehow?

**Comment by wallamide** [comment]
I got these fixed up. The hover now looks more like the original version: 
image

and the ToC now has more equal white space bordering: 
Screenshot from 2023-02-24 11-58-15

I'm unsure how to replicate @alice-i-cecile's issue with clicking on my end.

**Review by plof27 — APPROVED** [review]

**Pull request merged**
